routes/web.php
Route::get('/admin/course_results', 'GradeBookController@showCourseResult')->name('Course Results');
Route::get('/admin/downloadcourse', 'GradeBookController@downloadCourseExcelResults')->name('Download Course');

//semester results
Route::get('/admin/semster_results', 'GradeBookController@showSemesterResult')->name('Semester Results');
Route::get('/admin/download_semester', 'GradeBookController@downloadSemesterExcelResults')->name('Download SemesterExcel');

//nta semester results
Route::get('/admin/ntasemster_results', 'GradeBookController@showNtaSemesterResult')->name('NTA Semester Results');
Route::get('/admin/download_ntasemester', 'GradeBookController@downloadSemesterExcelResults')->name('Download NTA SemesterExcel');

//annual resullts
Route::get('/admin/annual_results', 'GradeBookController@showAnnualResult')->name('Annual Results');
Route::get('/admin/download_annualresults', 'GradeBookController@downloadAnnualResults')->name('Download Annual');

//transcript
Route::get('/admin/cand_transcript', 'GradeBookController@showCandidateTranscript')->name('Candidate Transcript');
Route::get('/admin/download_pdf', 'GradeBookController@downloadtranscriptPdf')->name('Download PDF');

//statement
Route::get('/admin/cand_statement', 'GradeBookController@showCandidateStatement')->name('Candidate Statement');
Route::get('/admin/downloadst_pdf', 'GradeBookController@downloadStatementPdf')->name('Downloadst PDF');

//supplementary
Route::get('/admin/supp_rpt', 'GradeBookController@showSupplementaryReport')->name('Supplimetary Report');
Route::get('/admin/downloadst_rpt', 'GradeBookController@downloadSuppRptPdf')->name('Downloadrpt PDF');

//REGISTRAR
//policy setup
Route::get('/admin/sponsor', 'SponsorsController@index')->name('sponsor');
Route::post('/admin/sponsor-add', 'SponsorsController@store')->name('sponsor.add');
Route::get('/admin/sponsor/{id}', 'SponsorsController@show')->name('Sponsor/Details');
Route::post('/admin/sponsor/{id}', 'SponsorsController@update')->name('sponsor.edit');
Route::post('/admin/sponsor-dlt/{id}','SponsorsController@destroy')->name('sponsor.dlt');

//admission
Route::get('/admin/regform', 'RegistrationFormController@index')->name('registration form');
Route::post('/admin/student-add', 'RegistrarController@store')->name('student.add');

Route::get('/admin/classlist', 'RegistrarController@index')->name('Classlists');
Route::get('/admin/classlistview/{regno}', 'RegistrarController@show')->name('classlist view');

//import student
Route::get('/admin/imprtstd', 'RegistrarController@showImport')->name('Import Students');
Route::post('/admin/uploadstd', 'RegistrarController@import')->name('Upload Students');

//student search
Route::get('/admin/searchstdnt', 'RegistrarController@studentsearch')->name('Student Search');
Route::get('/admin/showuploadpicture/{regno}', 'RegistrarController@showuploadpicture')->name('show upload picture');
Route::post('/admin/uploadpicture', 'RegistrarController@uploadpicture')->name('upload picture');

//accommodation
Route::resource('hostels', 'HostelController');

//restore logs
Route::get('/admin/dltedstudents', 'RegistrarController@showrestoreLogs')->name('Show Deleted Students');
Route::post('/admin/delete_complted', 'RegistrarController@completedelete')->name('complete delete');
Route::post('/admin/restorestudents', 'RegistrarController@studentrestore')->name('restore deleted');

//all
Route::get('/admin/profile', 'HomeController@profile')->name('profile');



Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

Route::resource('roles', 'Admin\RolesController');
Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
Route::resource('users', 'Admin\UsersController');
Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
Route::resource('teams', 'Admin\TeamsController');
Route::post('teams_mass_destroy', ['uses' => 'Admin\TeamsController@massDestroy', 'as' => 'teams.mass_destroy']);
Route::resource('products', 'Admin\ProductsController');
Route::post('products_mass_destroy', ['uses' => 'Admin\ProductsController@massDestroy', 'as' => 'products.mass_destroy']);
Route::post('products_restore/{id}', ['uses' => 'Admin\ProductsController@restore', 'as' => 'products.restore']);
Route::delete('products_perma_del/{id}', ['uses' => 'Admin\ProductsController@perma_del', 'as' => 'products.perma_del']);

Route::get('/team-select', ['uses' => 'Auth\TeamSelectController@select', 'as' => 'team-select.select']);
Route::post('/team-select', ['uses' => 'Auth\TeamSelectController@storeSelect', 'as' => 'team-select.select']);

});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('admin/change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('admin/change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');



//NEXT OF KIN
Route::post('nextkin','NextOfKinController@store');
Route::delete('nextkin/{nextOfKin}','NextOfKinController@destroy');


//DEPENDANTS 
Route::post('dependants','DependantController@store');
Route::delete('dependants/{dependant}','DependantController@destroy');

//EDU - BACKGROUND
Route::post('edu-histry','EducationHistryController@store');
Route::delete('edu-histry/{id}','EducationHistryController@destroy');

//BANK INFO 
Route::post('bank-info','BankInfoController@store');
Route::delete('bank-info/{bankInfo}','BankInfoController@destroy');


//USER PHOTO
Route::post('photo-upload','UserPhotoController@store');


//STUDENT CONTACTS StudentContactController
Route::get('student-contacts/{regno}','StudentContactController@create');
Route::post('student-contacts','StudentContactController@store');

//FILTER STUDENTS
Route::post('filter-students','StudentController@filter');
Route::get('filter-students', 'RegistrarController@studentsearch')->name('Student Search');



//SPONSOR
Route::get('sponsor-info/{regno}','StudentSponsorController@index');
Route::post('sponsor-info','StudentSponsorController@store');
Route::patch('student-sponsors','StudentSponsorController@update');


//PAYMENTS
Route::resource('payments','PaymentTypeController');

//Student Payments
Route::get('student-payments/{id}','StudentPaymentController@index');
Route::post('student-payment','StudentPaymentController@store');
Route::delete('student-payment/{id}','StudentPaymentController@destroy');


//Attachment controller
Route::resource('attachments','AttachmentController');


//Student Attachment student-attachment
Route::get('student-attachment/{std}','StudentAttachmentController@index');
Route::post('student-attachments/{std}','StudentAttachmentController@store');
Route::post('update-student-attachments','StudentAttachmentController@update');
Route::delete('remove-attachment/{att}','StudentAttachmentController@destroy');



//EXAM CATEGORY
Route::get('admin/examcategory','ExamCategoryController@index')->name('Exam Category');
Route::post('categories','ExamCategoryController@store')->name('categories');
Route::get('/admin/examcategory/{cat}', 'ExamCategoryController@show')->name('examcategory/preview');
Route::patch('/admin/examcategory/{cat}', 'ExamCategoryController@update')->name('examcategory.edit');



//INTAKE CATEGORIES
Route::get('/admin/intake-category','IntakeCategoryController@index')->name('intake-categories');
Route::post('/admin/intake-add', 'IntakeCategoryController@store')->name('intake.add');
Route::get('/admin/intake/{intake}', 'IntakeCategoryController@show')->name('Intake-Category/Details');
Route::post('/admin/intake-category/{id}', 'IntakeCategoryController@update')->name('intake.edit');
Route::post('/admin/intake-category-dlt/{id}', 'IntakeCategoryController@destroy')->name('int.dlt');


//Module configuration
Route::get('admin/programe/{id}/module-configure','ModuleConfigurationController@index')->name('module configuration');
Route::post('module configure','ModuleConfigurationController@store')->name('module configure');
Route::get('/admin/prog-module/{id}/edit','ModuleConfigurationController@edit');
Route::patch('update program module','ModuleConfigurationController@update')->name('update program module');
Route::post('delete-progr-module','ModuleConfigurationController@destroy')->name('delete-progr-module');


//Credit configuration 
Route::get('admin/programe/{id}/credit-configure','CreditConfigurationController@index')->name('credit configuration');
Route::post('credit configure','CreditConfigurationController@store')->name('credit configure');
Route::get('/admin/prog-credit/{id}/edit','CreditConfigurationController@edit');
Route::patch('update program credit','CreditConfigurationController@update')->name('update program credit');
Route::post('delete-progr-credit','CreditConfigurationController@destroy')->name('delete-progr-credit');


//STudy Level
Route::get('/admin/studylevel', 'StudyLevelController@index')->name('study level');

Route::get('/admin/studylevel/{stdylevel}', 'StudyLevelController@show')->name('studylevel/Details');
Route::post('/admin/stdylevel-add', 'StudyLevelController@store')->name('stdylevel.add');
Route::post('/admin/studylevel/{id}', 'StudyLevelController@update')->name('stdylevel.edit');

app/Team.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Team
 *
 * @package App
 * @property string $name
*/
class Team extends Model
{
    protected $fillable = ['name'];
    protected $hidden = [];
    
    public function members()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/Admin/TeamsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Product;
use App\Team;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreTeamsRequest;
use App\Http\Requests\Admin\UpdateTeamsRequest;

class TeamsController extends Controller
{
    /**
     * Display a listing of Team.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('team_access')) {
            return abort(401);
        }
        $teams = Team::all();

        return view('admin.teams.index', compact('teams'));
    }

    /**
     * Show the form for creating new Team.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('team_create')) {
            return abort(401);
        }

        return view('admin.teams.create');
    }

    /**
     * Store a newly created Team in storage.
     *
     * @param  \App\Http\Requests\StoreTeamsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTeamsRequest $request)
    {
        if (! Gate::allows('team_create')) {
            return abort(401);
        }
        $team = Team::create($request->all());

        return redirect()->route('admin.teams.index');
    }


    /**
     * Show the form for editing Team.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('team_edit')) {
            return abort(401);
        }
        $team = Team::findOrFail($id);

        return view('admin.teams.edit', compact('team'));
    }

    /**
     * Update Team in storage.
     *
     * @param  \App\Http\Requests\UpdateTeamsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTeamsRequest $request, $id)
    {
        if (! Gate::allows('team_edit')) {
            return abort(401);
        }
        $team = Team::findOrFail($id);
        $team->update($request->all());

        return redirect()->route('admin.teams.index');
    }


    /**
     * Display Team.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('team_view')) {
            return abort(401);
        }
        $team = Team::findOrFail($id);
        $products = Product::where('created_by_team_id', $id)->get();
        $users = User::whereHas('teams', function ($q) use ($id) {
            $q->where('id', $id);
        })->get();

        return view('admin.teams.show', compact('team', 'products', 'users'));
    }


    /**
     * Remove Team from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('team_delete')) {
            return abort(401);
        }
        $team = Team::findOrFail($id);
        $team->delete();

        return redirect()->route('admin.teams.index');
    }

    /**
     * Delete all selected Team at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('team_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Team::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }
}

resources/views/admin/teams/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title"  style="margin-top: 100px;">@lang('quickadmin.teams.title') </h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.teams.store']]) !!}

    <div class="panel panel-default" >
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', trans('quickadmin.teams.fields.name').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/teams/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.teams.title')</h3>
    
    {!! Form::model($team, ['method' => 'PUT', 'route' => ['admin.teams.update', $team->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', trans('quickadmin.teams.fields.name').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/teams/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title" style="margin-top: 20px;">@lang('quickadmin.teams.title')</h3>
    @can('team_create')
    <p>
        <a href="{{ route('admin.teams.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($teams) > 0 ? 'datatable' : '' }} @can('team_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('team_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.teams.fields.name')</th>
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($teams) > 0)
                        @foreach ($teams as $team)
                            <tr data-entry-id="{{ $team->id }}">
                                @can('team_delete')
                                    <td></td>
                                @endcan

                                <td field-key='name'>{{ $team->name }}</td>
                                                                <td>
                                    @can('team_view')
                                    <a href="{{ route('admin.teams.show',[$team->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('team_edit')
                                    <a href="{{ route('admin.teams.edit',[$team->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('team_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.teams.destroy', $team->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('team_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.teams.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/teams/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title" style="margin-top: 20px;">@lang('quickadmin.teams.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.teams.fields.name')</th>
                            <td field-key='name'>{{ $team->name }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#products" aria-controls="products" role="tab" data-toggle="tab">Products</a></li>
<li role="presentation" class=""><a href="#users" aria-controls="users" role="tab" data-toggle="tab">Users</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="products">
<table class="table table-bordered table-striped {{ count($products) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.products.fields.name')</th>
                        <th>@lang('quickadmin.products.fields.description')</th>
                        <th>@lang('quickadmin.products.fields.created-by')</th>
                        <th>@lang('quickadmin.products.fields.created-by-team')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($products) > 0)
            @foreach ($products as $product)
                <tr data-entry-id="{{ $product->id }}">
                    <td field-key='name'>{{ $product->name }}</td>
                                <td field-key='description'>{!! $product->description !!}</td>
                                <td field-key='created_by'>{{ $product->created_by->name or '' }}</td>
                                <td field-key='created_by_team'>{{ $product->created_by_team->name or '' }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('product_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.products.restore', $product->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('product_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.products.perma_del', $product->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('product_view')
                                    <a href="{{ route('admin.products.show',[$product->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('product_edit')
                                    <a href="{{ route('admin.products.edit',[$product->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('product_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.products.destroy', $product->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="9">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="users">
<table class="table table-bordered table-striped {{ count($users) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.users.fields.name')</th>
                        <th>@lang('quickadmin.users.fields.email')</th>
                        <th>@lang('quickadmin.users.fields.role')</th>
                        <th>@lang('quickadmin.users.fields.team')</th>
                                                <th>&nbsp;</th>

        </tr>
    </thead>

    <tbody>
        @if (count($users) > 0)
            @foreach ($users as $user)
                <tr data-entry-id="{{ $user->id }}">
                    <td field-key='name'>{{ $user->name }}</td>
                                <td field-key='email'>{{ $user->email }}</td>
                                <td field-key='role'>{{ $user->role->title or '' }}</td>
                                <td field-key='team'>{{ $user->team->name or '' }}</td>
                                                                <td>
                                    @can('user_view')
                                    <a href="{{ route('admin.users.show',[$user->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('user_edit')
                                    <a href="{{ route('admin.users.edit',[$user->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('user_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.users.destroy', $user->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="11">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.teams.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop